oc_platform_home:
    path:      /{page}
    defaults:
        _controller: OCPlatformBundle:Advert:index
        page: 1
    requirements:
        page: \d*

oc_platform_view:
    path:      /advert/{id}
    defaults: { _controller: OCPlatformBundle:Advert:view }
    requirements:
         id: \d+

oc_platform_add:
    path:      /add
    defaults: { _controller: OCPlatformBundle:Advert:add }

oc_platform_edit:
    path:    /edit/{id}
    defaults:
        _controller: OCPlatformBundle:Advert:edit
    requirements:
        id: \d+

oc_platform_delete:
    path:    /delete/{id}
    defaults:
        _controller: OCPlatformBundle:Advert:delete
    requirements:
        id: \d+

#oc_platform_background:
#    path:      /background/{id}
#    defaults:
#        _controller: OCPlatformBundle:Advert:background
#        id: 0
#    requirements:
#        id: \d*
#
#oc_platform_music:
  #  path:      /music
  #  defaults:
  #      _controller: OCPlatformBundle:Advert:music
oc_platform_background:
    path:      /background/{id}
    defaults:
        _controller: OCPlatformBundle:Extra:background
        id: 0
    requirements:
        id: \d*

oc_platform_music:
    path:      /music
    defaults:
        _controller: OCPlatformBundle:Extra:music
