<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBnilaot\appProdDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBnilaot/appProdDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerBnilaot.legacy');

    return;
}

if (!\class_exists(appProdDebugProjectContainer::class, false)) {
    \class_alias(\ContainerBnilaot\appProdDebugProjectContainer::class, appProdDebugProjectContainer::class, false);
}

return new \ContainerBnilaot\appProdDebugProjectContainer(array(
    'container.build_hash' => 'Bnilaot',
    'container.build_id' => '6364d723',
    'container.build_time' => 1517904529,
));
