<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBvsbbkg\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBvsbbkg/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerBvsbbkg.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerBvsbbkg\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerBvsbbkg\appProdProjectContainer(array(
    'container.build_hash' => 'Bvsbbkg',
    'container.build_id' => '9565c309',
    'container.build_time' => 1516883188,
));
