<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAsqhrui\appProdDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAsqhrui/appProdDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerAsqhrui.legacy');

    return;
}

if (!\class_exists(appProdDebugProjectContainer::class, false)) {
    \class_alias(\ContainerAsqhrui\appProdDebugProjectContainer::class, appProdDebugProjectContainer::class, false);
}

return new \ContainerAsqhrui\appProdDebugProjectContainer(array(
    'container.build_hash' => 'Asqhrui',
    'container.build_id' => 'ff5649a0',
    'container.build_time' => 1518705941,
));
