<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWpefpua\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWpefpua/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerWpefpua.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerWpefpua\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerWpefpua\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Wpefpua',
    'container.build_id' => 'fe6ad42a',
    'container.build_time' => 1518601863,
));
