<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerN9ouvvk\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerN9ouvvk/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerN9ouvvk.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerN9ouvvk\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerN9ouvvk\appDevDebugProjectContainer(array(
    'container.build_hash' => 'N9ouvvk',
    'container.build_id' => '86b2442e',
    'container.build_time' => 1517844655,
));
